# Site settings
title: LUMIX Breaks
client:
  name: LUMIX
  link: "#client-name"
core-se-link: https://www.secretescapes.com/current-sales
description: >
  Discover your new travel partner – the Panasonic LUMIX TZ100. Its compact size belies the quality and sharpness of the images it captures, with a Leica lens and 10x zoom offering outstanding photos in a small, travel-friendly package. 

# file paths
url:     "http://mp.secretescapes.com" # the base hostname & protocol for your site
baseurl: "/lumix" # the subpath of your site, e.g. /blog/
img:     "/lumix/_assets/img"
css:     "/lumix/_assets/css"
js:      "/lumix/_assets/js"


# Build settings
markdown: kramdown
exclude: [node_modules, gulpfile.js, package.json, package-lock.json, js/script.js]
keep_files: [_assets]
sass:
    sass_dir: css
    style: compressed